---
title: "Exp 2 Proprioception analysis: Clamp Adaptation"
output: html_notebook
---

```{r}
rm(list = ls())

text_size <- 14
options(digits = 4) 
library(tidyverse)
library(ggpubr)
library(pracma)
library(dplyr)
library(plotrix)
library(lemon)

dispersion1 <- function(P1x, P1y){
  distance1 = sqrt( (P1x - mean(P1x, na.rm = TRUE))^2 + (P1y - mean(P1y, na.rm = TRUE))^2)
  my.dispersion = mean(distance1, na.rm = TRUE)
  return(my.dispersion)
}

dispersion2 <- function(P1x, P1y, P2x, P2y){
  distance1 = sqrt( (P1x - mean(P1x, na.rm = TRUE))^2 + (P1y - mean(P1y, na.rm = TRUE))^2)
  distance2 = sqrt( (P2x - mean(P2x, na.rm = TRUE))^2 + (P2y - mean(P2y, na.rm = TRUE))^2)
  my.dispersion = mean(c(distance1, distance2), na.rm = TRUE)
  return(my.dispersion)
}

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}

data_summary_med <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = median(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}

data_summary_grp <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sem = std.error(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}

th <- theme(   panel.grid.major = element_blank(),
               panel.grid.minor = element_blank(),
               panel.border = element_blank(),
               panel.background = element_blank(),
               axis.line = element_line(size = 0.5), 
               legend.position = 'right', 
               legend.text = element_text(size= text_size, family="Helvetica"),
               text = element_text(size= text_size, family="Helvetica"), 
               strip.text.x = element_text(size = rel(0.90)), 
               strip.text.y = element_text(size = rel(0.90)), 
               axis.text.x = element_text(size = rel(0.85)),
               axis.text.y = element_text(size = rel(0.85)),
               axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0), angle = 90), 
               axis.title.x = element_text(vjust=-0.3), 
               plot.title = element_text(hjust = 0.5, vjust = 0), 
               axis.ticks.length=unit(0.25, "cm"), 
               axis.ticks = element_line(size = 0.5))
my.colors <-  c("#006600", "#800080", "#FF9900", 'deepskyblue4')
my.colors2 <-  c("#006600", "#800080", "#FF9900", 'deepskyblue4')

```


Load Data and Define Parameters 
```{r}

e2.data <- read.csv('~/Dropbox/MOTOR/proprioception/Data/E2_processed_data.csv', header=TRUE, sep=",") %>%
  mutate(Direction = ifelse(rot_cond == 15, 'CCW', 'CW')) %>% 
  mutate(Hand = hand_theta) %>% 
  select(SN, TN, CN, Direction, Hand, ti, fbi, MT, RT, FC_bias_X, FC_bias_Y, prop_theta, PropLocX, PropLocY, ri, PropTestAng)

e2.hand <- e2.data %>%  
  select(SN, TN, CN, Direction, ri, Hand, ti, fbi, MT, RT) %>%
  drop_na

e2.prop <- e2.data %>%
  select(SN, TN, CN, Direction,  FC_bias_X, FC_bias_Y, prop_theta, PropLocX, PropLocY, PropTestAng) %>%
  drop_na

reach.tar <- sort(unique(e2.hand$ti))
num.reach.tar <- length(reach.tar)
num.reach.trials <- nrow(e2.hand[e2.hand$SN == 1, ])

subjects <- unique(e2.hand$SN)
num.subj <- length(subjects)

probetarget <- unique(e2.prop$PropTestAng)
num.probetest <- length(probetarget)
num.probe.trials <- nrow(e2.prop[e2.prop$SN == 1, ])

```

Remove Outliers (Don't do this yet: Flip Direction)
```{r}

subj_compile <-  setNames(as.data.frame(matrix(0, ncol = num.reach.tar * 2 + 2, nrow = num.subj)), 
                          c('SN', 'Direction',  sprintf('T%s_rm', reach.tar), sprintf('T%s_sd', reach.tar)))

subj_compile$SN <- subjects

for(si in 1:num.subj ){
  for(mi in 1:num.reach.tar ){
    idx_sub <- e2.hand$SN == subjects[si] & e2.hand$ti == reach.tar[mi] 
    smoothed_sd <- sd( e2.hand$Hand[idx_sub] - movavg(e2.hand$Hand[idx_sub], 5, type=c("s"))) 
    idx_remove <- ( abs(e2.hand$Hand[idx_sub] - movavg(e2.hand$Hand[idx_sub], 5, type=c("s"))))  > 3*smoothed_sd
    
    smoothed_RT_sd <- sd( e2.hand$RT[idx_sub] - movavg(e2.hand$RT[idx_sub], 5, type=c("s")))
    idxRT_remove <- ( abs(e2.hand$RT[idx_sub] - movavg(e2.hand$RT[idx_sub], 5, type=c("s"))))  > 3*smoothed_RT_sd
    
    e2.hand$RT[idx_sub][idxRT_remove] <- NaN
    e2.hand$Hand[idx_sub][idx_remove] <- NaN
    
    subj_compile[ subj_compile$SN == subjects[si], sprintf('T%s_rm', reach.tar[mi]) ] <- length(e2.hand$Hand[idx_sub][idx_remove])
    
    subj_compile[ subj_compile$SN == subjects[si], sprintf('T%s_sd', reach.tar[mi]) ] <-  smoothed_sd
    subj_compile[ subj_compile$SN == subjects[si], 'Direction'] <- unique(e2.hand$Direction[idx_sub])
  }
}


# Proprioception
subjprop_compile <-  setNames(as.data.frame(matrix(0, ncol = 5, nrow = num.subj)), 
                              c('SN',  'Direction',  'Num_Rm', 'SD', 'PropVar_Rm'))

subjprop_compile$SN <- subjects

for(si in 1:num.subj ){
  idx_sub <- e2.prop$SN == subjects[si] 
  smoothed_sd <- sd( e2.prop$prop_theta[idx_sub] - movavg(e2.prop$prop_theta[idx_sub], 10, type=c("s")), na.rm = TRUE) 
  idx_remove <- ( abs(e2.prop$prop_theta[idx_sub] - movavg(e2.prop$prop_theta[idx_sub], 10, type=c("s"))))  > 99*smoothed_sd
  idx_remove[ is.na(idx_remove) ] <- FALSE
  idx_sub[ is.na(idx_sub) ] <- FALSE
  
  e2.prop$prop_theta[idx_sub][idx_remove] <- NaN
  
  subjprop_compile[ subjprop_compile$SN == subjects[si], 'Num_Rm' ] <- length(e2.prop$prop_theta[idx_sub][idx_remove])
  subjprop_compile[ subjprop_compile$SN == subjects[si], 'SD' ] <-  smoothed_sd
  subjprop_compile[ subjprop_compile$SN == subjects[si], 'Direction'] <- unique(e2.prop$Direction[idx_sub])[1]
  
  center_x <- mean ( e2.prop$FC_bias_X[idx_sub], na.rm = TRUE)
  center_y <- mean ( e2.prop$FC_bias_Y[idx_sub], na.rm = TRUE)
  sd_x <- sd ( e2.prop$FC_bias_X[idx_sub], na.rm = TRUE)
  sd_y <- sd ( e2.prop$FC_bias_Y[idx_sub], na.rm = TRUE)
  idx_propremove_x <- ( abs(e2.prop$FC_bias_X - center_x) > 3*sd_x ) 
  idx_propremove_y <- ( abs(e2.prop$FC_bias_Y - center_y) > 3*sd_y ) 
  idx_propremove_y[ is.na(idx_propremove_y) ] <- FALSE
  idx_propremove_x[ is.na(idx_propremove_x) ] <- FALSE
  
  e2.prop[idx_sub & (idx_propremove_x | idx_propremove_y), ] <- NaN
  
  subjprop_compile[ subjprop_compile$SN == subjects[si], 'PropVar_Rm'] <- nrow(e2.prop[idx_sub & (idx_propremove_x | idx_propremove_y), ])
}


```

Flip CW vs CCW
```{r}

e2.prop$prop_theta[e2.prop$Direction == 'CCW'] <- -e2.prop$prop_theta[e2.prop$Direction == 'CCW'] 
e2.hand$Hand[e2.hand$Direction == 'CCW'] <- -e2.hand$Hand[e2.hand$Direction == 'CCW'] 

```

Baseline Subtraction 
```{r}

bias_compile <-  setNames(as.data.frame(matrix(0, ncol = num.reach.tar + 2, nrow = num.subj)), 
                          c('SN', 'Direction',  sprintf('T%s_bias', reach.tar)))
bias_compile$SN <- subjects

for(si in 1:num.subj){
  for(mi in 1:num.reach.tar){
    idx_sub <- e2.hand$SN == subjects[si] & e2.hand$ti == reach.tar[mi]
    idx_bl <- idx_sub & e2.hand$CN >= 2 & e2.hand$CN <= 4     #9 -- 12
    sub_mean <- mean(e2.hand$Hand[idx_bl], na.rm = TRUE)
    idx_bl2 <- idx_sub & e2.hand$CN >= 10 & e2.hand$CN <= 12 
    sub_mean2 <- mean(e2.hand$Hand[idx_bl2], na.rm = TRUE)
    e2.hand$Hand[idx_sub] <- e2.hand$Hand[idx_sub] - sub_mean2
    
    RT_mean <- mean(e2.hand$RT[idx_bl2], na.rm = TRUE)
    e2.hand$RT[idx_sub] <- e2.hand$RT[idx_sub] - RT_mean
    
    bias_compile[ bias_compile$SN == subjects[si], sprintf('T%s_bias', reach.tar[mi]) ] <- sub_mean2
    bias_compile[ bias_compile$SN == subjects[si], 'Direction'] <- unique(e2.hand$Direction[idx_sub])
  }
}


biasprp_compile <-  setNames(as.data.frame(matrix(0, ncol = 20, nrow = num.subj)), 
                          c('SN', 'Direction',  sprintf('T%s_bias', probetarget), 
                            sprintf('T%s_var', probetarget) ))
biasprp_compile$SN <- subjects

for(si in 1:num.subj){
  for(mi in 1:num.probetest){
      idx_sub <- e2.prop$SN == subjects[si] & e2.prop$PropTestAng == probetarget[mi]
      idx_bl <- idx_sub & e2.prop$CN >= 17 & e2.prop$CN <= 20 & e2.prop$PropTestAng == probetarget[mi]
      idx_sub[ is.na(idx_sub) ] <- FALSE
      idx_bl[ is.na(idx_bl) ] <- FALSE
      
      sub_mean <- mean(e2.prop$prop_theta[idx_bl], na.rm = TRUE)
      sub_sd <- sd(e2.prop$prop_theta[idx_bl], na.rm = TRUE)
      e2.prop$prop_theta[idx_sub] <- e2.prop$prop_theta[idx_sub] - sub_mean
      
      biasprp_compile[ biasprp_compile$SN == subjects[si] , sprintf('T%s_bias', probetarget[mi])] <- sub_mean
      biasprp_compile[ biasprp_compile$SN == subjects[si] , sprintf('T%s_var', probetarget[mi])] <- sub_sd
      biasprp_compile[ biasprp_compile$SN == subjects[si], 'Direction'] <- unique(e2.prop$Direction[idx_sub])
  }
}

```


Plot Group
```{r}

e2.ind.hand <- e2.hand %>% 
  data_summary(varname = 'Hand', groupnames = c('SN', 'TN', 'fbi', 'Direction'))

e2.ind.prop <- e2.prop %>%
  data_summary(varname = 'prop_theta', groupnames = c('SN', 'TN', 'Direction'))

# collapse across ind
e2.grp.hand <- e2.ind.hand %>% 
  data_summary_grp(varname = 'Hand', groupnames = c('TN', 'fbi'))

e2.grp.prop <- e2.ind.prop %>% 
  data_summary_grp(varname = 'prop_theta', groupnames = c('TN')) %>%
  drop_na()

e2.learnhand <- e2.grp.hand

# setwd("~/Desktop")
# write.csv(e2.learnhand,"Learn_ParvinE2.csv")
# write.csv(e2.grp.prop,"Prop_ParvinE2.csv")

ref.lines <- c(9.5, 36.5,  72.5,  108.5, 144.5, 180.5, 270.5, 360.5, 396.5, 486.5, 522.5, 612.5, 648.5, 738.5)

my.grp.plot <- ggplot(data = e2.learnhand, aes(x = TN, y = Hand)) + 
  annotate('segment', x = 0, xend = 750, y = 0, yend = 0) + 
  annotate('segment', x = ref.lines, xend = ref.lines, y = -10, yend = 30, linetype = 'dotted', color = 'grey') + 
  annotate('rect', xmin = 9.5, xmax = 36.5, ymin = -10, ymax = 30, fill = 'grey', alpha = 0.6) + 
  annotate('rect', xmin = 36.5, xmax = 108.5, ymin = -10, ymax = 30, fill = 'grey', alpha = 0.2) + 
  
  geom_point(color = my.colors[1], alpha = 0.65, size = 1) + 
  geom_ribbon(data = e2.learnhand[e2.learnhand$TN <= 144.5, ], aes(x = TN, ymin = Hand - sem, ymax = Hand + sem), alpha = 0.2, fill = my.colors[1], inherit.aes = FALSE) + 
  geom_ribbon(data = e2.learnhand[e2.learnhand$TN >= 180.5 & e2.learnhand$TN <= 360.5, ], aes(x = TN, ymin = Hand - sem, ymax = Hand + sem), alpha = 0.2, fill = my.colors[1], inherit.aes = FALSE) + 
  geom_ribbon(data = e2.learnhand[e2.learnhand$TN >= 396.5 & e2.learnhand$TN <=  486.5, ], aes(x = TN, ymin = Hand - sem, ymax = Hand + sem), alpha = 0.2, fill = my.colors[1], inherit.aes = FALSE) + 
    geom_ribbon(data = e2.learnhand[e2.learnhand$TN >= 522.5 & e2.learnhand$TN <=  612.5, ], aes(x = TN, ymin = Hand - sem, ymax = Hand + sem), alpha = 0.2, fill = my.colors[1], inherit.aes = FALSE) + 
      geom_ribbon(data = e2.learnhand[e2.learnhand$TN >= 648.5 & e2.learnhand$TN <=  738.5, ], aes(x = TN, ymin = Hand - sem, ymax = Hand + sem), alpha = 0.2, fill = my.colors[1], inherit.aes = FALSE) + 
  
  geom_point(data = e2.grp.prop, aes(x = TN, y = prop_theta), inherit.aes = FALSE, color = my.colors[2], alpha = 0.65, size = 1) + 
   geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN <= 9 , ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
       geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN >= 108.5 & e2.grp.prop$TN <=  180.5, ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
         geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN >= 360.5 & e2.grp.prop$TN <=  396.5, ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
           geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN >= 486.5 & e2.grp.prop$TN <=  522.5, ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
            geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN >= 612.5 & e2.grp.prop$TN <=  648.5, ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
              geom_ribbon(data = e2.grp.prop[e2.grp.prop$TN >= 738.5, ], aes(x = TN, ymin = prop_theta - sem, ymax = prop_theta + sem), alpha = 0.2, fill = my.colors[2], inherit.aes = FALSE) + 
  #scale_y_continuous(limits = c(-10, 30)) + 
  scale_x_continuous(limits = c(0, 750), breaks = seq(0, 750, 250)) +
  coord_capped_cart(left = 'both', bottom = 'both') +
  labs(x = 'Trial Number', y = 'Hand Angle (°)') +
  th + theme(axis.title.y = element_text(margin = margin(l = 0, r = 7, t = 0, b = 0)), text = element_text(size=22)) 
print(my.grp.plot)

```



Summary Parameters 
```{r}

hand_param <- setNames(as.data.frame(matrix(NaN, ncol = 48, nrow = num.subj)), 
                       c('SN', 'Direction', 'Early_Adapt', 'Late_Adapt', 'CB2', 'CB3', 'CB4', 
                         'PB0', 'PB1', 'PB2','PB3', 'PB4', 'PB5', 
                         'PBvar0', 'PBvar1', 'PBvar2','PBvar3', 'PBvar4', 'PBvar5', 
                         'PBvarall', 'PBshiftall', 
                         sprintf('Early_T%s', reach.tar), sprintf('Late_T%s', reach.tar), sprintf('PB1_T%s', probetarget) ))

prop_start <- c(1, 109, 360, 487, 613, 739)
prop_end <- c(9, 180, 396, 522, 649, 774)

counter <- 1
for(si in 1:num.subj){
  
  
  idx.hand <- e2.ind.hand$SN == subjects[si] 
  idx.prop <- e2.ind.prop$SN == subjects[si] 
  
  hand_param$SN[counter] <- subjects[si]
  hand_param$Direction[counter] <- unique(e2.hand$Direction[e2.hand$SN == si])
  hand_param$Base_Early[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 17 & e2.ind.hand$TN <=  36 ], na.rm = TRUE)
  hand_param$Base_Late[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 37 & e2.ind.hand$TN <=  108], na.rm = TRUE)
  
  hand_param$Early_Adapt[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 186 & e2.ind.hand$TN <=  235], na.rm = TRUE) / 50
  hand_param$Late_Adapt[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >=  523  & e2.ind.hand$TN <= 738], na.rm = TRUE)
  
  hand_param$CB0[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 81 & e2.ind.hand$TN <=   108], na.rm = TRUE) 
  hand_param$CB1[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 269 & e2.ind.hand$TN <=  359], na.rm = TRUE) 
  hand_param$CB2[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 397 & e2.ind.hand$TN <=  487], na.rm = TRUE) 
  hand_param$CB3[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 523 & e2.ind.hand$TN <=  613], na.rm = TRUE)
  hand_param$CB4[counter] <- mean(e2.ind.hand$Hand[idx.hand & e2.ind.hand$TN >= 649 & e2.ind.hand$TN <=  739], na.rm = TRUE) 
  
  for(mi in 1:6){
    idx_var <- e2.prop$SN == si & e2.prop$TN >= prop_start[mi] & e2.prop$TN <= prop_end[mi] 
    hand_param[counter, sprintf('PB%s', mi - 1)] <- mean(e2.ind.prop$prop_theta[idx.prop & e2.ind.prop$TN >= prop_start[mi] &  e2.ind.prop$TN <= prop_end[mi]], na.rm = TRUE)
    hand_param[counter, sprintf('PBvar%s', mi - 1)] <- sd ( e2.prop$prop_theta[idx_var] , na.rm = TRUE) 
  }
  counter <- counter + 1
}


counter = 1
for(si in 1:num.subj){
  
  idx_var1 <- e2.prop$SN == si & e2.prop$TN >= prop_start[2] & e2.prop$TN <= prop_end[2]
  idx_var2 <- e2.prop$SN == si & e2.prop$TN >= prop_start[2] 
  
  hand_param[counter, 'PBvarbase'] <- dispersion1(e2.prop$FC_bias_X[idx_var1], e2.prop$FC_bias_Y[idx_var1])
  hand_param[counter, 'PBvarall'] <- dispersion2(e2.prop$FC_bias_X[idx_var1], e2.prop$FC_bias_Y[idx_var1], e2.prop$FC_bias_X[idx_var2], e2.prop$FC_bias_Y[idx_var2])
  hand_param[counter, 'PBvarall_ang'] <- sd ( e2.prop$prop_theta[idx_var2] , na.rm = TRUE)
  
 
  
  idx_shift1 <- e2.prop$SN == si & e2.prop$TN >= prop_start[3] 
  hand_param[counter, 'PBshiftall'] <- mean(e2.prop$prop_theta[idx_shift1], na.rm = TRUE)
  
  #hand_param[counter, 'Propbias'] <- biaspropsum$Propbasebias[biaspropsum$SN == si]
  #hand_param[counter, 'Propbiasandshift'] <- biaspropsum$Propbasebias[biaspropsum$SN == si] + mean(e2.prop$prop_theta[idx_shift1], na.rm = TRUE)
  
  counter = counter + 1
}

# setwd("~/Desktop")
# write.csv(hand_param,"HandParam_ParvinE2.csv")


```

Correlations
```{r}

ae.plot <- hand_param %>% gather(cond, value, c('CB0', 'CB1', 'CB2', 'CB3', 'CB4')) %>% 
  mutate(cond2 = case_when(cond == 'CB0' ~ 'CB0', 
                           cond == 'CB1' ~ 'CB1', 
                           cond == 'CB2' ~ 'CB2', 
                           cond == 'CB3' ~ 'CB3', 
                           cond == 'CB4' ~ 'CB4', 
                           cond == 'CB5' ~ 'CB5') )  %>% 
  ggplot(aes(x = cond2, y = value)) + 
  geom_line(inherit.aes = FALSE, aes(x = cond2, y = value, group = SN), color = my.colors[1], alpha = 0.1) + #
  geom_boxplot(fill =   my.colors[1], width = 0.25, outlier.shape = NA, alpha = 0.5, size = 0.5) + 
  stat_summary(fun = 'mean', geom = 'point', color = 'black', size = 2) + 
  scale_y_continuous(breaks = seq(-0, 60, 30)) + 
  coord_capped_cart(left = 'both', bottom = 'both', ylim = c(-10, 60)) +
  labs(x = ' ', y = 'Hand Angle (°)') +
  th + facet_wrap(.~Direction)
print(ae.plot)

```

```{r}

ps.plot <- hand_param %>% gather(cond, value, PB1:PB5) %>% 
  mutate(cond2 = case_when(cond == 'PB1' ~ 'PB0', 
                           cond == 'PB2' ~ 'PB1', 
                           cond == 'PB3' ~ 'PB2', 
                           cond == 'PB4' ~ 'PB3', 
                           cond == 'PB5' ~ 'PB4', 
                           cond == 'PB6' ~ 'PB5') )  %>% 
  ggplot(aes(x = cond2, y = value)) + 
  geom_line(inherit.aes = FALSE, aes(x = cond2, y = value, group = SN), color = my.colors[2], alpha = 0.1) + 
  geom_boxplot(fill =   my.colors[2], width = 0.25, outlier.shape = NA, alpha = 0.5) + 
  stat_summary(fun = 'mean', geom = 'point', color = 'black', size = 2) + 
  scale_y_continuous(breaks = seq(-60, 60, 30)) + 
  coord_capped_cart(left = 'both', bottom = 'both') +
  labs(x = ' ', y = 'Proprioceptive Error (°)') +
  th
print(ps.plot)

```

```{r}

pv.plot <- hand_param %>% gather(cond, value, PBvar1:PBvar5) %>% 
  mutate(cond2 = case_when(cond == 'PBvar0' ~ 'PBx)', 
                           cond == 'PBvar1' ~ 'PB0', 
                           cond == 'PBvar2' ~ 'PB1', 
                           cond == 'PBvar3' ~ 'PB2', 
                           cond == 'PBvar4' ~ 'PB3', 
                           cond == 'PBvar5' ~ 'PB4') )  %>% 
  ggplot(aes(x = cond2, y = value)) + 
  geom_line(inherit.aes = FALSE, aes(x = cond2, y = value, group = SN), color = my.colors2[4], alpha = 0.1) + 
  geom_boxplot(fill =   my.colors2[4], width = 0.25, outlier.shape = NA, alpha = 0.5) + 
  stat_summary(fun = 'mean', geom = 'point', color = 'black', size = 2) + 
  scale_y_continuous(limits = c(0, 30, breaks = seq(0, 30, 10))) + 
  scale_x_discrete(expand=c(0,0.6)) + 
  coord_capped_cart(left = 'both', bottom = 'both') +
  labs(x = ' ', y = 'Proprioceptive Variability (°)') +
  th 
print(pv.plot)

```


Correlations between propangvar and aftereffect
```{r}

af.pvall.cor.ang <- hand_param %>% 
  ggplot(aes(x = PBvarall_ang, y = Late_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', size = 3) + 
  ggpubr::stat_cor(method = 'spearman', aes(x = PBvarall_ang, y = Late_Adapt), size = 6, label.y = 50) + 
  #scale_y_continuous(limits = c(10, 35), breaks = seq(10, 35, 5)) + 
  scale_x_continuous(limits = c(4, 25)) +
  #facet_grid(.~Day) + 
  labs(x = 'Proprioceptive Variability (°)', y = 'Asymptote (°)') + 
  coord_capped_cart(left = 'top', bottom = 'right') +
  #scale_alpha_continuous(range = c(0.1, 1)) + 
  th
print(af.pvall.cor.ang)


```


Correlations between parameters 
```{r}


af.pvall.cor <- hand_param %>% 
  ggplot(aes(x = PBvarall, y = Late_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', size = 3, alpha = 1) + 
  ggpubr::stat_cor(method = 'spearman', aes(x = PBvarall, y = Late_Adapt), size = 6, label.y = 50) + 
  #scale_y_continuous(limits = c(10, 35), breaks = seq(10, 35, 5)) + 
  #scale_x_continuous(limits = c(10, 40)) +
  #facet_grid(.~Day) + 
  labs(x = 'Proprioceptive Variability (mm)', y = 'Asymptote (°)') + 
  coord_capped_cart(left = 'top', bottom = 'right') +
  th
print(af.pvall.cor)

```

```{r}

af.ps.cor <- hand_param %>% 
  mutate(colorcode = ifelse(abs(PBshiftall)<10, 1, 0)) %>%
  ggplot(aes(x = PBshiftall, y = Late_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point( size = 2, alpha = 1, aes(color = factor(colorcode))) + 
  stat_cor(method = 'pearson', aes(x = PBshiftall, y = Late_Adapt), size = 6, p.digits = 1, label.x = -10) + 
  #scale_y_continuous( limits = c(10, 35), breaks = seq(10, 35, 5)) + 
  scale_x_continuous(limits = c(-30, 35), breaks = seq(-30, 30, 10)) +
  #facet_grid(.~Day) + 
  scale_color_manual(values = c('black', 'red'), guide = FALSE) + 
  labs(x = 'Proprioceptive Shift (°)', y = 'Asymptote (°)') + 
  coord_capped_cart(left = 'top', bottom = 'right') +
  th 
print(af.ps.cor)

```

```{r}

pv.ps.cor <- hand_param %>% 
  ggplot(aes(x = PBvarall_ang, y = PBshiftall)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', size = 3, alpha = 1) + 
  stat_cor(method = 'pearson', aes(x = PBvarall_ang, y = PBshiftall), size = 6, label.y = 38) + 
  #scale_y_continuous(limits = c(-30, 40), breaks = seq(-30, 40, 10)) + 
  scale_x_continuous(limits = c(4, 25)) +
  #facet_grid(.~Day) + 
  labs(x = 'Proprioceptive Variability ((°)', y = 'Proprioceptive Shift (°)') + 
  coord_capped_cart(left = 'top', bottom = 'right') +
  th
print(pv.ps.cor)

```


```{r}

af.ps.cor2 <- hand_param %>% 
  filter(abs(PBshiftall) < 10) %>%
  ggplot(aes(x = PBshiftall, y = Late_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'red', alpha = 0.2) + 
  geom_point( size = 2, alpha = 1, color = 'red') + 
  #stat_cor(method = 'pearson', aes(x = PBshiftall, y = Late_Adapt), size = 6, p.digits = 1, label.x = -10, label.y = -2) + 
  #scale_y_continuous( limits = c(10, 35), breaks = seq(10, 35, 5)) + 
  scale_x_continuous(limits = c(-8,4), breaks = seq(-8, 4, 4)) +
  #facet_grid(.~Day) + 
  labs(x = ' ', y = ' ') + 
  coord_capped_cart(left = 'top', bottom = 'right') +
  th + theme(axis.line = element_line(color = 'red'), axis.text = element_text(color = 'red'), axis.ticks = element_line(color = 'red'))
print(af.ps.cor2)

```



```{r}

early.pv.cor <- hand_param %>% 
  ggplot(aes(x = PBvarall, y = Early_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', alpha = 1) + 
  ggpubr::stat_cor(method = 'spearman', aes(x = PBvarall, y = Early_Adapt)) + 
  labs(x = 'Proprioceptive Variability (mm)', y = 'Early Adapt (°)') + 
  th
print(early.pv.cor)

setwd("~/Desktop")
ggsave("early_pv_cor.pdf",
       plot = early.pv.cor, height = 3, width = 3.5,  units = "in")

```

```{r}

early.ps.cor <- hand_param %>% 
  ggplot(aes(x = PBshiftall, y = Early_Adapt)) +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', alpha = 0.2) + 
  geom_point(color = 'black', size = 1, alpha = 1) + 
  ggpubr::stat_cor(method = 'spearman', aes(x = PBshiftall, y = Early_Adapt)) + 
  #scale_y_continuous(limits = c(10, 35), breaks = seq(10, 35, 5)) + 
  #scale_x_continuous(limits = c(10, 40)) +
  #facet_grid(.~Day) + 
  labs(x = 'Proprioceptive Shift (°)', y = 'Early Adapt (°)') + 
  #coord_capped_cart(left = 'top', bottom = 'right') +
  th
print(early.ps.cor)

setwd("~/Desktop")
ggsave("early_ps_cor.pdf",
       plot = early.ps.cor, height = 3, width = 3.5,  units = "in")


```




